### ISSUE TITLE
Bug in the qemu shell script?

### ISSUE THREAD

**Issue by zero0nee** [clearkimura/Customizer#11]
When I try to run gemu from the gui on Ubuntu 12.04 I get the following error:
[_] Executing qemu at: 04:53:10 PM/12-07-2012
[_] Checking whether X is running
[_] Getting the configs
[_] Running QEMU with ISO image: /home/Minimalism-i386-12.04.iso
/opt/Customizer/scripts/qemu: line 41: qemu: command not found
[X] An error accure while trying to emulate the ISO

The problem is that "qemu" is not a valid command. Changing "qemu -cdrom" to "qemu-system-i386 -cdrom" on line 41 in the qemu shell script should solve the problem.

**Comment by fluxer** [comment]
Fixed, thank you very much!

If you have Ubuntu 10.04 (Lucid) I would appreciate if you can see if the command 'qemu-system-i386' will work on it too because I don't have Ubuntu (nor any Debian derivative) installed just to make sure it won't brake the compability with the older Ubuntu releases.

I will leave the issue open for now but if you are sure it works fine close it when desired.
