### ISSUE TITLE
Unable to squash the filesystem

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#13]
I'm testing Customizer 3.2.3 to rebuild my remix.

All features works, except when rebuilding ISO, it returns error "Unable to squash the filesystem".

The error apparently mentions invalid option when including "-wildcards -ef .." option.
This is regardless whichever compression method I'm using.

When I removed the "-wildcards -ef .." option from the "rebuild" script file, 
 I managed to rebuild ISO as per usual.

Any workaround or fix for this?

**Comment by fluxer** [comment]
As a start execute the following in a terminal:

mksquashfs -version > info.txt
uname -a >> info.txt
lsb_release -a >> info.txt
cd /opt/Customizer && ./CLI -r | tee -a info.txt

and [Gist](https://gist.github.com) info.txt so I can take a look at it. Cheers!

**Comment by ghost** [comment]
The last command (./CLI -r | tee -a info.txt) didn't work, so I copied the Terminal output directly.

Created as private gist at URL below:
https://gist.github.com/43018f526d0b39f79c11

Have a look.

**Comment by fluxer** [comment]
I see you are running Lucid. The issue is caused by unsupported 'comp' flag so either use squashfs-tools package that is newer verions backported for Lucid or modify the script to fix this.

I don't know if Ubuntu Lucid 10.04 is still supported by the Ubuntu community but I will drop support for it for sure soon and I'm not interested in implementing a fix for this.

Closing issue with status 'will not fix'. Cheers!

**Comment by fluxer** [comment]
Fixed in both master and gambas3 branches via 21f04b0 and d0d89bc.
