### ISSUE TITLE
Error when compiling on Ubuntu 13.10

### ISSUE THREAD

**Issue by Gubolin** [clearkimura/Customizer#34]
1) The ppa does not include files for 13.10

2) When I want to build it, it tries to install gambas2, which does not exist, either. Gambas3 does.

3) After fixing this issues, you will notice that "CLI.sh -g" will try to check "/home/FileSystem/", which does, of course, not exist.

Edit:
4) 'gksu /opt/Customizer/GUI.gambas' does not work after trying to tweak everything.

Edit2:
5) Even the CLI does not work for me. "The ISO image doesn't exists." (<- Typo!)

**Comment by ghost** [comment]
@Gubolin 
Let me answer your question one by one:

1) PPA is discouraged for newer releases of Ubuntu; which makes PPA relevant only up to 12.04 Precise release. Use install.sh script instead.

2) Are you trying to force install from PPA in this step? Anyway, Ubuntu 12.10 and newer should use Gambas3 port. If you must use Gambas2 port (master branch), you will have to install gambas2 packages using third party PPA.

3), 4), 5) Rather than trying to force install from PPA (which is outdated) and trying to do unnecessary fixing, try install Gambas3 port on your Ubuntu 13.10, using install.sh script.

P.S.:   We almost never receive feedbacks from users regarding installation and usage on 12.10 and newer. We have no volunteer to do further test install or use on newer platform, due to lack of feedback and resources.

P.S.S.:   Don't install development version; this is totally different from existing branches and experimental. Always use stable version and install from script.

**Comment by Gubolin** [comment]
Ok, it was also quite confusing to me.

With building, I meant using install.sh. I didn't try to force ppa install.
Here is what happens with install.sh:
Checking dependencies
 (passed, except gbr2)
Checking distribution
 (updates package list)
 package gambas2-gb-form not available
 package gambas2-runtime not available
 [...]
Error: Unable to install the dependencies.

Let me be your volunteer, I'll help to make it compatible.

**Comment by ghost** [comment]
@Gubolin 
We would be glad to hear your feedback, regardless of failure or success. You just need to share with us what host system in use (in your case, Ubuntu 13.10), which branch do you use (either master or gambas3) and which ISO did you successfully/failed to customize.

Back to your issue, to install Gambas 3 port using script, you must pass the wildcard option to the command:

```
 sudo ./install.sh -b gambas3 -i
```

You can refer to our official user guide for more details.

Did you managed to install Gambas 3 port now?

**Comment by Gubolin** [comment]
Cool. It worked :+1:  I successfully installed Customizer :>
You should implement a check to do so automatically.

Now I'll try it out; this will probably take a while. There are no errors so far, I can open the GUI without problems.

**Comment by ghost** [comment]
@Gubolin 
Noted your suggestion. Should you wish to feedback, please send to us by email.
Thank you for using Customizer!
For now, I will close this issue.

**Comment by ghost** [comment]
For time being, I have updated instructions under [FAQ](https://github.com/fluxer/Customizer/wiki/FAQ) on how to install for Ubuntu 12.10 or newer releases ( i.e. how to install gambas 3 port ). Installation from PPA is not recommended, unless the packages are updated.

Personally, I don't prefer to fix something that isn't broken ( refering to the install.sh script ).
