### ISSUE TITLE
Desktop not working?

### ISSUE THREAD

**Issue by Gubolin** [clearkimura/Customizer#35]
It's probably not your fault.

I try to customize Ubuntu 13.10 GNOME 32-bit on Ubuntu 13.10 64-bit. After installing some packages with the chrooted terminal, I wanted to open the desktop with the desktop button. Now customizer asks me whether to run 
- gnome-classic
- gnome
- ubuntu

I tried all three, but all I get is a black window "Xephyr" and a cursor. How to fix?
For example, if I try to run "gnome", it seems to stop at
*\* (update-notifier:25315): WARNING *_: not starting for system user
(deja-dup-monitor:25322): GVFS-RemoteVolumeMonitor-WARNING *_: remote volume monitor with dbus name org.gtk.Private.UDisks2VolumeMonitor is not supported

**Comment by ghost** [comment]
@Gubolin 
This issue has at least two unknowns.

[1]   I have never tested customizing a 32-bit ISO on 64-bit host. The other way round (customizing 64-bit ISO on 32-bit host) has been noted in our official user guide, under Limitations chapter--nothing much you can do (although I am not aware how much you can customize in this condition either).

[2]   I have never tested GNOME 3 releases (a.k.a GNOME shell) nor Unity desktop environment in recent Ubuntu releases either. So I can't tell whether it actually works or not.

The short answer is, I don't know how to fix it.

The long answer is quite long.. so I will only explain in brief.

One possible reason is, the use of new window manager, Clutter in GNOME 3. If you didn't know, the elementary OS 0.2, codename Luna, also uses GNOME 3 as their base environment. And if you ever tried loading in VirtualBox, it barely responds well. Single core CPU is nonetheless slow. This is because compositing manager is turned on and cannot be turned off like GNOME 2.

The blank screen may be resulting from this reason.

Then again, I don't experience blank screen with other distribution ISO that uses compositing manager, such as elementary OS 0.2 (but Desktop background is not drawn in Xephyr, can only see solid color) and Xubuntu 12.04 (compositing manager is turned off by default in Xephyr, but can be enabled from Control Panel, no difference in Desktop background).

Above all, this issue is may be exclusive for GNOME 3 only.

What I can suggest is, try customize the ISO and host with same architecture i.e. customize a 32-bit ISO on 32-bit host system, or 64-bit ISO on 64-bit host system. And feedback to us the result.

**Comment by ghost** [comment]
@Gubolin 
This is more like a user feedback on host system and ISO image compatibility, rather than issue with Customizer itself. My apologies if I am not being helpful. Because we don't have enough information or feedback from users, we can't give proper solution for each and every issues on compatibility matter.

Regarding feedback method, I am planning to create a simple survey form for users in several weeks time. When the time comes, please help us fill in the survey.

It has been few days without feedback, so I am closing this issue for now.
Feel free to reopen this issue, once you have time to do further testing.
