### ISSUE TITLE
Change default wallpaper of new users desktop

### ISSUE THREAD

**Issue by mbnoimi** [clearkimura/Customizer#43]
How can I change the default wallpaper of new users and LiveDVD user?
I don't know how can I do it from "Desktop" button!

**Comment by mbnoimi** [comment]
May I get any help guys?

**Comment by fluxer** [comment]
Well, you don even provide info about the Desktop Environment in use.
And in any case this has nothing to with Customizer - to change
the wallpaper you need to know how the DE does it, the one that pops
when you click on the "Desktop" button.

The files for the Live CD/DVD user are located in /etc/skel which is
used as a skeleton with various files that should be copied to $HOME
for every user added (the Live CD/DVD user is created during the boot).

Good luck!

**Comment by mbnoimi** [comment]
@fluxer 

Thanks for help.

> Well, you don even provide info about the Desktop Environment in use.

Sorry my mistake. I'm using Linux Mint 16 Cinnamon x64

> And in any case this has nothing to with Customizer - to change
> the wallpaper you need to know how the DE does it, the one that pops
> when you click on the "Desktop" button.

When I clicked "Desktop" button I could change the root user wallpaper but all the created new uses still get same old default mint wallpaper and I couldn't know how to change wallpaper of LiveDVD user

> The files for the Live CD/DVD user are located in /etc/skel which is
> used as a skeleton with various files that should be copied to $HOME
> for every user added (the Live CD/DVD user is created during the boot).

but /etc folder is full of configurations how can I know the exact path of the default user & livedvd users?

**Comment by fluxer** [comment]
> Sorry my mistake. I'm using Linux Mint 16 Cinnamon x64

Now we are doing it :)

> When I clicked "Desktop" button I could change the root user wallpaper but all the created new uses still get
> same old default mint wallpaper and I couldn't know how to change wallpaper of LiveDVD user

That's an issue, usually the root configs are copied over to /etc/skel so that the changes apply to thew new users
too. In the development version this is no longer the case - all changes done go to /etc/skel directly which is
much better but not perfect too I guess. You can try to delete the content of /etc/skel (in chroot!):

 rm -rf /etc/skel/.*

run the nested X-session again, customize, rebuild and see if the your changes apply.

> but /etc folder is full of configurations how can I know the exact path of the default user & livedvd users?

I have no idea really. Cinnamon is too buggy and I never played too much with it. You should search the Linux
Mint forums for topics about it, I guess someone has asked the question there already. Should be something in
/etc/skel/.config/cinnamon/wallpaper.conf or whatever.

**Comment by ghost** [comment]
@mbnoimi 
Whenever new user is created, it will be based on changes you have made to root setting via `Desktop` feature in Customizer GUI, which is then copied and found at `../etc/skel`, as mentioned by @fluxer earlier.

For example, GNOME 2.30 keeps its background configuration under $HOME directory, whose path is `~/.gconf/desktop/gnome/background/%gconf.xml`. This is however, just serves an example from which I know on Ubuntu 10.04 (uses GConf and now discontinued).

The newer releases of GNOME and Cinnamon however, no longer use this method but uses DConf instead. In regard of Cinnamon or such recent interface, that is as far as I know.

Kindly look up on other places which may offer better advice. Building an Ubuntu-based remix or spin is not common by end-users, thus one might not find answers readily. This is why one may ended up trying a lot of errors, to actually get what he/she wants.

Anyway, since this is _not_ an issue related to Customizer, I will mark as "Invalid" and closing this issue.

**Comment by mbnoimi** [comment]
@clearkimura 

> Anyway, since this is not an issue related to Customizer, I will mark as "Invalid" and closing this issue.

I wonder where can I ask you any question about Customizer other than here?

**Comment by fluxer** [comment]
> I wonder where can I ask you any question about Customizer other than here?

You can send me an email, if it's covered by the user guide I will tell you to read it tough (which you should have done anyway).

**Comment by mbnoimi** [comment]
> You can send me an email, if it's covered by the user guide I will tell you to read it tough (which you should have done anyway).

I think this project needs forum OR mailing-list for supporting the community just like other open source projects... does it?

**Comment by fluxer** [comment]
@mbnoimi Can you support such a thing? Because I do not have time for this really.

**Comment by mbnoimi** [comment]
@fluxer I can but how can I do it while I'm still a newbie in Customizer and in Linux remastering in general.

**Comment by hreikin** [comment]
@fluxer @mbnoimi  i can set up a forum for customizer if you wish but it will probably have to be this weekend

http://customizer.freeforums.org

^^ i knocked that up in 10 mins, will finish updating all sections with relevant posts tomorrow/this weekend, i need to sleep now for a couple of hours before night shift :(

if you have any suggestions for sections/what to include then let me know

**Comment by ghost** [comment]
@hreikin 

> if you have any suggestions for sections/what to include then let me know

Forum may be easier to setup than finding committees. The question now is, anyone willing to attend each and every submission by users?

> @mbnoimi Can you support such a thing? Because I do not have time for this really.

At least, @fluxer had given his answer already. And I can't either.
Any committed volunteers?

P.S.: Rather than discussing here, perhaps we should open this discussion as "new issue"..

**Comment by mbnoimi** [comment]
@clearkimura 
Hey this is not my comment! I didn't say:

> Can you support such a thing? Because I do not have time for this really.
