### ISSUE TITLE
The filesystem is locked

### ISSUE THREAD

**Issue by mbnoimi** [clearkimura/Customizer#47]
After installing some packages by "Install DEB" recently I'm unable to add new packages by using same button

```
[*] Executing extract at: CET 07:14:12 /26-01-2014
[*] Checking lock
[X] The filesystem is locked
```

How can I fix this issue without deleting current project and create a new project?

**Comment by mbnoimi** [comment]
To fix this issue I manually removed "$WORK_DIR/FileSystem/tmp/lock_chroot" so I wonder does it affect on the resultant remastered iso?

**Comment by ghost** [comment]
@mbnoimi 
Your fix is correct. In fact, we have mentioned this issue in our official user guide (in Subchapter 4.2, filed as ISSUE-2011-005). As far as I know, no effect on remastered ISO.

Remember to always use `exit` command to close the chroot Terminal.

But this issue can also happen if you attempt to stop process (perhaps you press `Ctrl`+`C`) while updating repositories. Uncheck the option in `File` > `Settings` -- Use apt-helper ( Default is enabled ) if you find Customizer keep running updates everytime you use any customization buttons.

Consider this as a limitation with workaround. So we won't fix this.

**Comment by ghost** [comment]
@mbnoimi 
By the way, there is another way of installing DEB without using `Install DEB` button.

This alternative method assumes that your remix has a Desktop Environment, a File Browser and `gdebi` package been installed.
1.  In Customizer, File menu bar, select `Directories` then `FileSystem`. A File Browser will open as root.
2.  Navigate to `tmp` directory and leave it open at side
3.  Back to Customizer, click on `Desktop` button and wait until the Live Desktop window fully loads
4.  Switch back to the File Browser you opened earlier, and you can see few temporary files being created because you are running Live Desktop via Xephyr. Copy the DEB files to this directory.
5.  Switch back the Live Desktop window and navigate to `tmp` directory. You will see the content is same as what you can view from host system File Browser earlier.
6.  Double-click on one DEB file at a time to install (or, you can use `dpkg -i` command in Terminal)

This is something like shared folder feature that you can find in VirtualBox PUEL. Except, once you close the Live Desktop window, all files in `tmp` directory will be deleted. This is why you must copy DEB files **after** you have click on `Desktop` button.
