### ISSUE TITLE
Cannot set default locale to english

### ISSUE THREAD

**Issue by abrsdk** [clearkimura/Customizer#6]
the default locale is in Russian but i dont want that. i tried to find locale English but its not listed. help please!

**Comment by fluxer** [comment]
Yeah, I missed that. 3-options here:
1. I should fix it (see bellow)
2. You can edit the config file (/opt/Customizer/settings.conf) and use Customizer as usual but if you open the settings dialog the value of LOCALES will be changed and you have to edit the config file again
3. Again edit the config file but use Customizer from CLI, the variable won't change unless you do it

1 is not going to happen anytime soon, it needs some tinkering so the best way to set the locales in the chroot is used. Imagine if the user wants to set the locales to Russian, for an example, but they are not present (missing because they were not installed in the first place, purged by localepurge or whatever the reason) so Customizer needs to check what locales are available and add only valid values for those in a list. It's not hard but I need to know exactly how the locales work (locations for them, config files etc.) and this takes time which I don't want to invest in Customizer anymore because I don't use Ubuntu for some time.

Feedback and patches about locales are welcome!

**Comment by abrsdk** [comment]
So i just changed the locale in settings to en_US, will that work?

**Comment by fluxer** [comment]
Correct.

**Comment by fluxer** [comment]
Ok, I've added 'C' and 'POSIX' to the locales list. If 'C' is choosed (it is the default now) the locales should be English now.
