### ISSUE TITLE
Support 14.04

### ISSUE THREAD

**Issue by jnarvaezp** [clearkimura/Customizer#61]
Customizer support 14.04 LTS?

Thanks

**Comment by ghost** [comment]
@gururea 
The support means two things. So your question can be either one:
1. Can Customizer be installed on 14.04 LTS host system?
2. Does Customizer supports 14.04 LTS ISO image file?

In short, yes for both.

For case 1., as long as you have dependencies of gambas.
- gambas2 (to install Customzier from master branch) or,
- gambas3 (to install Customizer from gambas3 branch).

You can independently add PPA repository for latest release of gambas, regardless of your Ubuntu release.

For case 2., as long as the ISO structure of Ubuntu doesn't change.

Since 12.04 LTS, one small changes we realize is the content of `/etc/lsb-release`, which has been added with `export FLAVOUR="Ubuntu"` line (refer to issue #45 for details).

So, refining your questions:
- Have we tested on 14.04 LTS yet? No.
- Have we tested using 14.04 LTS ISO image yet? No.

I will eventually test it, but not any soon due to working condition.

We are lacking of volunteers and user feedbacks, so if you willing, you can test for us.

**Comment by lav0s** [comment]
Testing, 14.04 LTS, until now just a dependency problem with whoopsie and libpam, still testing

**Comment by ghost** [comment]
I did initial testing for Customizer 3.2.3 on Xubuntu 14.04, using Xubuntu 14.04 ISO image file. So far no problem, except some extra features not working, due to changes in recent releases.

One example is the boot loader; Ubuntu now uses `systemd-shim` (hence syslinux boot splash editor doesn't work anymore). Users can always look for alternative to change the Plymouth boot splash, either by installing theme via package manager or, do manually.

@lav0s 
I am unsure why the dependency problem `whoopsie` and `libpam-*` has to do with Customizer functionality. Because I didn't get any error message related to these packages.

**Comment by ghost** [comment]
Although basic features working fine, I cannot boot the newly rebuilded Xubuntu 14.04 ISO image in VirtualBox, while the original Xubuntu 14.04 ISO image was able to boot without problem.

Testing to be continued.

**Comment by ghost** [comment]
Regarding 14.04 support, existing Customizer can be installed on 14.04 host system. However, Customizer might not be able to properly rebuild the official ISO image files. Therefore, users are highly recommended to rebuild from Ubuntu Mini Remix ISO image file.

#### Case 1

I had tested with Xubuntu 14.04 ISO image file, using Customizer 3.2.3 (gambas3 branch).

Extract and customize ISO image file were successful, however the rebuilded ISO image file cannot be boot in QEMU nor VirtualBox emulator. I have repeated this process several times, using different compression method (xz and gzip). That didn't resolve "cannot be boot" issue.

##### Test result 1

Failed. The boot failed at very initial stage, doesn't even pass to boot splash menu. This is fatal error, something is wrong with official ISO image structure or technical complication.

#### Case 2

I had downloaded Ubuntu Mini Remix 14.04 (32-bit) and tested it using the same Customizer 3.2.3 (gambas3 branch).

Extract, customize and rebuild are all successful, which makes a perfect candidate to build your 14.04 remix. For my testing purpose, I had set up a minimal Desktop Environment with Linux generic kernel and headers, xserver-xorg, minimal xfce4 packages with lightdm login manager packages.

##### Test result 2

Success. This test remix was able to boot in QEMU and VirtualBox emulators respectively.

#### Remarks

I have not tested with other 14.04-based ISO image files (such as vanilla Ubuntu, Linux Mint, Kubuntu, et cetera). If you have ever tested any of these, kindly [submit your feedback here](https://docs.google.com/forms/d/17MVZtiSSmR3G-Qqy7Mbg1UejiQLefwMcyzro0gjawI8/viewform). This link to feedback form can also be found at [our Wiki page](https://github.com/clearkimura/Customizer/wiki).

Above all, I have confirmed myself that 14.04 support is still valid. Therefore, I am closing this issue.

**Comment by lav0s** [comment]
after try and try, all 14.04 isos, 32 or 64 from Ubuntu Vanilla are with the same problem

https://bugs.launchpad.net/ubuntu/+source/whoopsie/+bug/1272269

microfix tested, and working for whoopsie, there are other problems but are ubuntu specific, so yeah clearkimura, no problems with your app, initially i started to think, that maybe it was something.

for libpam, just hold the packages and it will do it's magic.

**Comment by lav0s** [comment]
not yours, confirmed on distro, so no worries :D

2014-07-29 15:30 GMT-05:00 clearkimura notifications@github.com:

**Comment by ghost** [comment]
@lav0s 
Glad to hear from someone (hardly anyone responds after I gave my recent testing feedback).
Thank you for your feedback!
