### ISSUE TITLE
WINE cannot be installed during the building process

### ISSUE THREAD

**Issue by thomasstevenson** [clearkimura/Customizer#62]
I'm using Customizer v3.2.3 on Ubuntu 14.04 amd64 (both host and build OSes).
After copying & pasting my host system's /etc/apt/sources.lst file into my build OS (which includes all of the default Ubuntu repositories), running <code>apt-get update</code> and attempting to install the wine1.6 package (using both Synaptic and the <code>apt-get install</code> Terminal command) I am left unable to install WINE to the build OS. The following is the Terminal output after attempting to do so:

<pre>
The following packages have unmet dependencies:
 wine1.6 : Depends: wine1.6-i386 (= 1:1.6.2-0ubuntu4) but it is not installable
           Recommends: gnome-exe-thumbnailer but it is not going to be installed or
                       kde-runtime but it is not going to be installed
           Recommends: fonts-horai-umefont but it is not going to be installed
           Recommends: fonts-unfonts-core but it is not going to be installed
           Recommends: ttf-wqy-microhei
           Recommends: winbind but it is not going to be installed
           Recommends: winetricks but it is not going to be installed
</pre>

When I look for the wine1.6-i386 package in Synaptic on the build system it doesn't show up even though it shows up on the host system with the same repositories. Performing an installation of the .deb package of wine1.6-i386 also doesn't fix the solution due to a long list of uninstallable dependencies. Adding the <code>--force-architecture</code> and <code>--force-depends</code> arguments also fail to install the package.

Please let me know if there is a workaround to this or if I'm doing something wrong.

**Comment by ghost** [comment]
@thomasstevenson 
First of all, this issue is very likely **not** due to Customizer. You will see such error messages when repositories are invalid, missing packages or not enabled.

In fact, other users also face this problem and it is not rare
-  [Can't install wine on Ubuntu 14.04 [duplicate]](http://askubuntu.com/questions/459280/cant-install-wine-on-ubuntu-14-04)

And the solutions and configurations related to Wine are these:
-  [How do I resolve unmet dependencies?](http://askubuntu.com/questions/140246/how-do-i-resolve-unmet-dependencies)
-  [Installing and Configuring Wine](http://askubuntu.com/questions/316025/installing-and-configuring-wine)

Since `wine1.6` is listed under **universe** repository, make sure it is enabled. Some of its dependencies also may require **multiverse** repository so enable this too. These are explained in quoted links anyway.

Just in case, please reply comment here and close this issue if solved.

**Comment by ghost** [comment]
@thomasstevenson 
On small note, I noticed that you are using Customizer on 14.04. We lack of feedbacks from users all the time, so we would be glad if you could spend few minutes on our user feedback survey.

The link to feedback survey form is found on [our Wiki page](https://github.com/fluxer/Customizer/wiki).

Thank you for using Customizer and we look forward to your feedback!

**Comment by thomasstevenson** [comment]
Thank you very much. Running the following commands fixed the issues:

<pre>
dpkg --add-architecture i386
apt-get update
apt-get install wine1.6
</pre>

I have also just answered the survey questions.

Thank you very much for the support and for the development of Customizer!

**Comment by ghost** [comment]
@thomasstevenson 
My bad, I just noticed the error message in second line, was actually telling that you are trying to install a 32-bit package (the keyword "-i386" squeezed between words), though you are using 64-bit system.

```
...
wine1.6 : Depends: wine1.6-i386 (= 1:1.6.2-0ubuntu4) but it is not installable
...
```

Frankly, I have been using only 32-bit system all the time.. which may explain why I didn't immediately realize this--insensitive on such issues related to 64-bit system.

Glad that you have found the solution! Since this has been solved, I am closing this issue.
