### ISSUE TITLE
Linux Mint 17 fails update

### ISSUE THREAD

**Issue by ShvonderSiN** [clearkimura/Customizer#63]
crashes error about the update.. nothing helps, even synaptic, in the end, you can make a distro without updates...With the previous version Mint had no such problems.

**Comment by ghost** [comment]
@ShvonderSiN 
We are unsure if your intention is to just leave a comment, or to request our help to solve this issue?

Even Customizer is no longer active in development, we can at least provide you a workaround (whenever possible). Without any useful information, we cannot do anything for you.

If you want a help to solve this issue, please follow [our submission guide](https://github.com/clearkimura/Customizer/issues/50).

**Comment by ShvonderSiN** [comment]
I myself did not understand seek help or is it just a comment.
But I would like to overcome this problem.
I add Linux Mint 17 ISO in the program. Open a terminal.
Write there the command: apt-get update && apt-get upgrade.
And at what stage is broken something and it does not improve.
Used to make the distribution of LinuxMint16 and no problems arose. For that thank you very much.
screenshot http://giveimg.com/di/4OUF/.png

**Comment by k3dar** [comment]
i'm not test with LinuxMint17, but have same problem with Ubuntu 14.04... (with host Ubuntu 12.10)
anyway this is not problem with customizer, but with libpam-systemd package, universal workaround is holt this package for update...

in chroot before you run apt-get upgrade run this:
apt-mark hold libpam-systemd

and after apt-get upgrade finish unhold back with this before rebuild iso:
apt-mark unhold libpam-systemd

if you plane use customized iso with preseeding installation, is also need hold kernel packages,
without this is break in first stage of pressed in setting language, maybe only with non-english settings as for me, or maybe is this already fixed in some of updates in Ubuntu 14.04/LinuxMint 17, i customized iso before some weeks..

hold before upgrade:
apt-mark hold linux-generic linux-headers-3.13.0-24 linux-headers-3.13.0-24-generic linux-headers-generic linux-image-3.13.0-24-generic linux-image-extra-3.13.0-24-generic linux-image-generic

unhold after upgrade:
apt-mark unhold linux-generic linux-headers-3.13.0-24 linux-headers-3.13.0-24-generic linux-headers-generic linux-image-3.13.0-24-generic linux-image-extra-3.13.0-24-generic linux-image-generic

**Comment by gmstyle** [comment]
@k3dar same problem with ubuntu 14.04 32bit for me. solved with hold libpam-systemd befor upgrading but i made an experiment :) i tried to upgrade the same iso with ubuntu-builder without holding nothing and the process works fine and end fine...the problem seems to appear only with customizer (4.1 and 3.2.3 too)

**Comment by fluxer** [comment]
Which flavour of Linux Mint 17 are we talking about? What architecture?

**Comment by ShvonderSiN** [comment]
both linux mint 17 (32 and 64), same problem

**Comment by fluxer** [comment]
It's a packaging issue:

> The following packages have unmet dependencies:
> libpam-systemd : Depends: systemd-services (= 204-5ubuntu20) but 204-5ubuntu20.5 is to be installed
> E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by gmstyle** [comment]
@fluxer but in your opinion why upgrading with ubuntu-builder there are not problems to do apt-get upgrade? using the same iso naturally...

**Comment by fluxer** [comment]
Gambas2 is not even available for Ubuntu 14.04 release so there is no
way to test it but looking at the code I better not comment on it.

**Comment by gmstyle** [comment]
ok thanks ;)
