### ISSUE TITLE
Help compiling

### ISSUE THREAD

**Issue by fe1a** [clearkimura/Customizer#71]
Hello @clearkimura Well I found your software and I need help compiling it

**Comment by hreikin** [comment]
@optrusty what do you mean compile it ? the installation instructions are in the README file as well as provided in the FAQ : 

https://github.com/clearkimura/Customizer#getting-started
https://github.com/clearkimura/Customizer/wiki/FAQ#how-can-i-install-and-run-customizer

Remember, if using 12.10 or newer you need the gambas3 package rather than the gambas2 one, you will need to enable the universe repository in your software sources list and then update before trying to install.

EDIT : Unless you are trying the devel branch, then clone the git repo, change into the customizer repo and follow the instructions here : 

https://github.com/clearkimura/Customizer/tree/devel#install-and-run
