### ISSUE TITLE
Copying files to chroot environment

### ISSUE THREAD

**Issue by kalabantas** [clearkimura/Customizer#77]
Hello, This is a question rather than an issue. I would like to copy files from the host machine to the chroot environment. I can't locate the mounted directories.
Appreciate your pointing me to these directories.
Thanks

**Comment by kalabantas** [comment]
Got it, through the Gui > directories.
Thanks

**Comment by ghost** [comment]
@kalabantas 
I suppose GUI is much self-explanatory, that is, for master and gambas3 branches' releases. 

Anyway, it is always good to check your working directory. This is where the chroot environment files are extracted from the ISO image file you have loaded. By default, it is under `/home`.

I won't explain much from here, since resources are accessible from [our GitHub Wiki](https://github.com/clearkimura/Customizer/wiki). The basic instructions are more or less sufficient, except some are _not_ applicable to current devel branch.

In related matter regarding your question, you may be interested to read [my reply in earlier issue](https://github.com/clearkimura/Customizer/issues/33#issuecomment-25294296) as well. This is something technical, which I didn't include in official resources.
