### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by psycato** [clearkimura/Customizer#8]
Is it possible to use xephyr to enter different users desktop?

Say, if I would like to set different desktopbackgrounds for different users, and not just for the root user.

regards,
Cato

**Comment by fluxer** [comment]
I will not implement that but you should be able to do so by modifying the common file, line 158 (https://github.com/fluxer/Customizer/blob/master/common). Just change "env HOME=/root..." to "env HOME=/home/<user>" to the desired user home directory. Note that the user must exists for this to work and the home directory should also be created. 

Line 88-90 should be deleted from xnest (https://github.com/fluxer/Customizer/blob/master/scripts/xnest) or the changes will also be saved for the other users (which are added later such as the live user).

It is not impossible but you'd better do it by hand by thinkering with configs files for the specifiec user (this depends on the desktop environment) or write a hook to do this for you to save you time when rebuilding ISOs rather than modifying scripts and losing the changes on the next update of Customizer.

**Comment by psycato** [comment]
Sounds easy enough.
Noted! Thanks again for the prompt reply!

C
