### ISSUE TITLE
errors on install deb and xnest and pkgm

### ISSUE THREAD

**Issue by kerroncheddie** [clearkimura/Customizer#9]
Errors were encountered while processing:
 /tmp/*.deb;
 apt-get
 install
 -f
 -y

env: export: No such file or directory

pkgm updates 3 times before opening
every call for chroot updates packages

**Comment by fluxer** [comment]
> pkgm updates 3 times before opening. every call for chroot updates packages

that's because **chroot** function is called 3 times to make sure everything is fine if any packages and such were installed but not configured and such, if it really bothers you uncheck (or just edit the config file) so that APT_HELPER is not set to true (1) in Main -> Settings.

> env: export: No such file or directory

should be fixed now

> Errors were encountered while processing:

provide more details when reporting bugs, I don't test Customizer much lately nor do I have magic ball to look at what's the issue you encountered.

**Comment by kerroncheddie** [comment]
"Errors were encountered while processing:
/tmp/*.deb;
apt-get
install
-f
-y"  
is the response i got with install deb.
sorry for being so vague.

**Comment by fluxer** [comment]
It should be fixed now. Install via the script or if you are running Ubuntu or derivative wait for the PPA to be updated.

**Comment by kerroncheddie** [comment]
checking now

**Comment by kerroncheddie** [comment]
still 
"dpkg: error processing /tmp/_.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 /tmp/_.deb"
seems as though the deb file isn't being copied to the tmp folder.
.......so i checked
but it is bieng copied......just not being installed or read properly.

**Comment by fluxer** [comment]
try now and report back

**Comment by kerroncheddie** [comment]
thats it mate .....sorted
